# Generated by Django 2.2.4 on 2023-04-07 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=256, verbose_name='电影详情链接')),
                ('img', models.CharField(max_length=256, verbose_name='电影图片链接')),
                ('name', models.CharField(max_length=256, verbose_name='电影名称')),
                ('engName', models.CharField(max_length=256, null=True, verbose_name='电影外文名')),
                ('score', models.FloatField(verbose_name='评分')),
                ('comNum', models.IntegerField(verbose_name='评价人数')),
                ('des', models.TextField(null=True, verbose_name='概况')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('guojia', models.CharField(max_length=256, null=True, verbose_name='国家')),
                ('kind', models.CharField(max_length=256, null=True, verbose_name='种类')),
                ('daoyan', models.CharField(max_length=256, null=True, verbose_name='导演')),
                ('zhuyan', models.TextField(null=True, verbose_name='主演')),
                ('pianchang', models.IntegerField(null=True, verbose_name='时长')),
                ('price', models.IntegerField(default=0, verbose_name='预测票房')),
            ],
            options={
                'verbose_name': '电影表',
                'verbose_name_plural': '电影表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('tel', models.CharField(max_length=64, unique=True, verbose_name='手机号')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('username', models.CharField(max_length=64, verbose_name='姓名')),
                ('sex', models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], max_length=4, null=True, verbose_name='性别')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='地址')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/', verbose_name='用户头像')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
            options={
                'verbose_name_plural': '收藏',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
            options={
                'verbose_name_plural': '浏览历史',
            },
        ),
    ]
