# Generated by Django 2.2.4 on 2024-02-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('categoryName', models.CharField(max_length=128, verbose_name='分类')),
                ('productName', models.CharField(max_length=128, verbose_name='品名')),
                ('unit', models.CharField(max_length=128, verbose_name='单位')),
                ('priceMax', models.FloatField(verbose_name='最高价')),
                ('priceAvg', models.FloatField(verbose_name='平均价')),
                ('priceMin', models.FloatField(verbose_name='最低价')),
                ('productSize', models.CharField(max_length=128, verbose_name='规格')),
                ('productPlace', models.CharField(max_length=128, verbose_name='产地')),
                ('recordDate', models.DateField(verbose_name='发布日期')),
            ],
            options={
                'verbose_name': '农产品管理',
                'verbose_name_plural': '农产品管理',
            },
        ),
        migrations.CreateModel(
            name='Rice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('sheng', models.CharField(max_length=128, verbose_name='省份')),
                ('pzlx', models.CharField(max_length=128, verbose_name='品种名称')),
                ('qbly', models.CharField(max_length=128, verbose_name='亲本来源')),
                ('lx', models.CharField(max_length=128, verbose_name='类型')),
                ('ycd', models.CharField(max_length=128, verbose_name='原产地')),
                ('sdbh', models.CharField(max_length=128, verbose_name='审定编号')),
                ('sdf', models.CharField(max_length=128, verbose_name='审定方')),
                ('sdxh', models.CharField(max_length=128, verbose_name='审定序号')),
                ('mb', models.CharField(max_length=128, verbose_name='母本')),
                ('sdgs', models.CharField(max_length=128, verbose_name='审定公司')),
                ('recordDate', models.DateField(verbose_name='发布日期')),
            ],
            options={
                'verbose_name': '水稻管理',
                'verbose_name_plural': '水稻管理',
            },
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': '浏览管理'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name_plural': '收藏管理'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': '电影管理', 'verbose_name_plural': '电影管理'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户管理', 'verbose_name_plural': '用户管理'},
        ),
    ]
