# Generated by Django 2.2.4 on 2024-02-28 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240228_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
